
name: ticker scrape

on:
  push:
    paths:
      - 'config/ticker.md'
  workflow_dispatch:
  schedule:
  # At minute 35 past every 2nd hour from 13 through 21 on every day-of-week from Monday through Friday.
    - cron:  '35 13-22/2 * * 1-5' 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Python requirements
      run: |-
        python -m pip install -U pip
        pip install -r .scripts/requirements.txt
    - name: Generate ticker report
      run: |-
        .scripts/ticker.py ${{ secrets.YFINANCE_API_KEY }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "TICKER Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
